export default {
    title: '君威 以雕塑美学 诠释潮流 ',
    detail: [
        {
            type: 'color',
            value: '#f00',
            data: [
                'https://www.buick.com.cn/img/newregal/360/red/01.png',
                'https://www.buick.com.cn/img/newregal/360/red/02.png',
                'https://www.buick.com.cn/img/newregal/360/red/03.png',
                'https://www.buick.com.cn/img/newregal/360/red/04.png',
                'https://www.buick.com.cn/img/newregal/360/red/05.png',
                'https://www.buick.com.cn/img/newregal/360/red/06.png',
                'https://www.buick.com.cn/img/newregal/360/red/07.png',
                'https://www.buick.com.cn/img/newregal/360/red/08.png',
                'https://www.buick.com.cn/img/newregal/360/red/09.png',
                'https://www.buick.com.cn/img/newregal/360/red/10.png',
                'https://www.buick.com.cn/img/newregal/360/red/11.png',
                'https://www.buick.com.cn/img/newregal/360/red/12.png',
                'https://www.buick.com.cn/img/newregal/360/red/13.png',
                'https://www.buick.com.cn/img/newregal/360/red/14.png',
                'https://www.buick.com.cn/img/newregal/360/red/15.png',
                'https://www.buick.com.cn/img/newregal/360/red/16.png',
                'https://www.buick.com.cn/img/newregal/360/red/17.png',
                'https://www.buick.com.cn/img/newregal/360/red/18.png',
                'https://www.buick.com.cn/img/newregal/360/red/19.png',
                'https://www.buick.com.cn/img/newregal/360/red/20.png',
                'https://www.buick.com.cn/img/newregal/360/red/21.png',
                'https://www.buick.com.cn/img/newregal/360/red/22.png',
                'https://www.buick.com.cn/img/newregal/360/red/23.png',
                'https://www.buick.com.cn/img/newregal/360/red/24.png',
                'https://www.buick.com.cn/img/newregal/360/red/25.png',
                'https://www.buick.com.cn/img/newregal/360/red/26.png',
                'https://www.buick.com.cn/img/newregal/360/red/27.png',
                'https://www.buick.com.cn/img/newregal/360/red/28.png',
                'https://www.buick.com.cn/img/newregal/360/red/29.png',
                'https://www.buick.com.cn/img/newregal/360/red/30.png',
                'https://www.buick.com.cn/img/newregal/360/red/31.png',
                'https://www.buick.com.cn/img/newregal/360/red/32.png',
                'https://www.buick.com.cn/img/newregal/360/red/33.png',
                'https://www.buick.com.cn/img/newregal/360/red/34.png',
                'https://www.buick.com.cn/img/newregal/360/red/35.png',
                'https://www.buick.com.cn/img/newregal/360/red/36.png',

            ]
        },
        {
            type: 'color',
            value: '#fff',
            data: [
                'https://www.buick.com.cn/img/newregal/360/white/01.png',
                'https://www.buick.com.cn/img/newregal/360/white/02.png',
                'https://www.buick.com.cn/img/newregal/360/white/03.png',
                'https://www.buick.com.cn/img/newregal/360/white/04.png',
                'https://www.buick.com.cn/img/newregal/360/white/05.png',
                'https://www.buick.com.cn/img/newregal/360/white/06.png',
                'https://www.buick.com.cn/img/newregal/360/white/07.png',
                'https://www.buick.com.cn/img/newregal/360/white/08.png',
                'https://www.buick.com.cn/img/newregal/360/white/09.png',
                'https://www.buick.com.cn/img/newregal/360/white/10.png',
                'https://www.buick.com.cn/img/newregal/360/white/11.png',
                'https://www.buick.com.cn/img/newregal/360/white/12.png',
                'https://www.buick.com.cn/img/newregal/360/white/13.png',
                'https://www.buick.com.cn/img/newregal/360/white/14.png',
                'https://www.buick.com.cn/img/newregal/360/white/15.png',
                'https://www.buick.com.cn/img/newregal/360/white/16.png',
                'https://www.buick.com.cn/img/newregal/360/white/17.png',
                'https://www.buick.com.cn/img/newregal/360/white/18.png',
                'https://www.buick.com.cn/img/newregal/360/white/19.png',
                'https://www.buick.com.cn/img/newregal/360/white/20.png',
                'https://www.buick.com.cn/img/newregal/360/white/21.png',
                'https://www.buick.com.cn/img/newregal/360/white/22.png',
                'https://www.buick.com.cn/img/newregal/360/white/23.png',
                'https://www.buick.com.cn/img/newregal/360/white/24.png',
                'https://www.buick.com.cn/img/newregal/360/white/25.png',
                'https://www.buick.com.cn/img/newregal/360/white/26.png',
                'https://www.buick.com.cn/img/newregal/360/white/27.png',
                'https://www.buick.com.cn/img/newregal/360/white/28.png',
                'https://www.buick.com.cn/img/newregal/360/white/29.png',
                'https://www.buick.com.cn/img/newregal/360/white/30.png',
                'https://www.buick.com.cn/img/newregal/360/white/31.png',
                'https://www.buick.com.cn/img/newregal/360/white/32.png',
                'https://www.buick.com.cn/img/newregal/360/white/33.png',
                'https://www.buick.com.cn/img/newregal/360/white/34.png',
                'https://www.buick.com.cn/img/newregal/360/white/35.png',
                'https://www.buick.com.cn/img/newregal/360/white/36.png',
            ]
        }
    ]
}

